<?php
//goldsmith
		
		$sql1 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,sum(rec_weight_gross) as gross_goldsmith,sum((rec_weight_gross-rec_weight_stone)) as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,0 as qty FROM " . DB_PREFIX . "bill_rec_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=0 and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		
		if (!empty($data['filter_name'])) {
			
			$sql1 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,sum(rec_weight_gross) as gross_goldsmith,sum((rec_weight_gross-rec_weight_stone)) as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,0 as qty FROM " . DB_PREFIX . "bill_rec_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=0 AND o.ornament_id='".$data['filter_name']."' and rec.branch='".$this->session->data['branch_id']."'  group by new_date,new_item_group";
		}	
		
		
		
		
		
		//purchase customer
		$sql2 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,sum(item_gross) as gross_purchase,sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billp_items as bill_item left join " . DB_PREFIX . "billp as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where bill_date < '" . $this->db->escape($from) . "' and bill_flag=0 and bill.branch='".$this->session->data['branch_id']."'  group by new_date,new_item_group";
		if (!empty($data['filter_name'])) {
			$sql2 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,sum(item_gross) as gross_purchase,sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billp_items as bill_item left join " . DB_PREFIX . "billp as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where bill_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill_flag=0 and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}
		
		//purchase Supplier
		$sql9 = "SELECT FROM_UNIXTIME(`stock_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,sum(item_gross) as gross_purchase,sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billp_items as bill_item left join " . DB_PREFIX . "billp as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where stock_date < '" . $this->db->escape($from) . "' and bill_flag=1 and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		if (!empty($data['filter_name'])) {
			$sql9 = "SELECT FROM_UNIXTIME(`stock_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,sum(item_gross) as gross_purchase,sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billp_items as bill_item left join " . DB_PREFIX . "billp as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where stock_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill_flag=1 and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}	
		
		//purchase Supplier Return
		$sql10 = "SELECT FROM_UNIXTIME(`stock_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,-1*sum(item_gross) as gross_purchase,-1*sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billpret_items as bill_item left join " . DB_PREFIX . "billpret as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where stock_date < '" . $this->db->escape($from) . "' and bill_flag=1 and bill.branch='".$this->session->data['branch_id']."'  group by new_date,new_item_group";
		if (!empty($data['filter_name'])) {
			$sql10 = "SELECT FROM_UNIXTIME(`stock_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,-1*sum(item_gross) as gross_purchase,-1*sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billpret_items as bill_item left join " . DB_PREFIX . "billpret as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where stock_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill_flag=1 and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}	
		
		//new purchase Customer Return
		$sql101 = "SELECT FROM_UNIXTIME(`stock_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,-1*sum(item_gross) as gross_purchase,-1*sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billpret_items as bill_item left join " . DB_PREFIX . "billpret as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where stock_date < '" . $this->db->escape($from) . "' and bill_flag=0 and bill.branch='".$this->session->data['branch_id']."'  group by new_date,new_item_group";
		if (!empty($data['filter_name'])) {
			$sql101 = "SELECT FROM_UNIXTIME(`stock_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,-1*sum(item_gross) as gross_purchase,-1*sum((item_gross-item_stone)) as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billpret_items as bill_item left join " . DB_PREFIX . "billpret as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "ornamnet as o on bill_item.item_code=o.ornament_code where stock_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill_flag=0 and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}	
		
		//hallmarking
		
		$sql3 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,sum(rec_weight_gross) as gross_hallmark,sum((rec_weight_gross-rec_weight_stone)) as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,0 as qty FROM " . DB_PREFIX . "bill_rec_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		if (!empty($data['filter_name'])) {
		
		
			$sql3 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,sum(rec_weight_gross) as gross_hallmark,sum((rec_weight_gross-rec_weight_stone)) as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,0 as qty FROM " . DB_PREFIX . "bill_rec_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 AND o.ornament_id='".$data['filter_name']."' and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}
		
		//sales
		
		$sql4 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,sum(item_gross)  as gross_sales,sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "bill_items as bill_item left join " . DB_PREFIX . "bill as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "' and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		
		if (!empty($data['filter_name'])) {
				$sql4 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,sum(item_gross)  as gross_sales,sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "bill_items as bill_item left join " . DB_PREFIX . "bill as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}

		//Order

		$sql14 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,sum(item_gross)  as gross_sales,sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net,-1*sum(bill_item.item_qty) as qty from " . DB_PREFIX . "billestorder_items as bill_item left join " . DB_PREFIX . "billestorder as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "' and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";

		if (!empty($data['filter_name'])) {
				$sql14 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,sum(item_gross)  as gross_sales,sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net,-1*sum(bill_item.item_qty) as qty from " . DB_PREFIX . "billestorder_items as bill_item left join " . DB_PREFIX . "billestorder as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		}
		
		//New sales Return customer
		
		$sql11 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,-1*sum(item_gross)  as gross_sales,-1*sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "bill_return_items as bill_item left join " . DB_PREFIX . "bill_return as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "' and bill.branch='".$this->session->data['branch_id']."' and bill.bill_flag='0' group by new_date,new_item_group";
		
		if (!empty($data['filter_name'])) {
				$sql11 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,-1*sum(item_gross)  as gross_sales,-1*sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "bill_return_items as bill_item left join " . DB_PREFIX . "bill_return as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill.branch='".$this->session->data['branch_id']."' and bill.bill_flag='0' group by new_date,new_item_group";
		}

		//Order Exchange Return customer

        $sql112 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,-1*sum(item_gross)  as gross_sales,-1*sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net,sum(bill_item.item_qty) as qty from " . DB_PREFIX . "billestorderret_items as bill_item left join " . DB_PREFIX . "billestorder as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "' and bill.branch='".$this->session->data['branch_id']."' and bill_item.item_code!='' group by new_date,new_item_group";

        if (!empty($data['filter_name'])) {
                $sql112 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,-1*sum(item_gross)  as gross_sales,-1*sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net,sum(bill_item.item_qty) as qty from " . DB_PREFIX . "billestorderret_items as bill_item left join " . DB_PREFIX . "billestorder as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill.branch='".$this->session->data['branch_id']."' and bill_item.item_code!='' group by new_date,new_item_group";
        }
		//New sales Return supplier
		
		$sql110 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,-1*sum(item_gross)  as gross_sales,-1*sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "bill_return_items as bill_item left join " . DB_PREFIX . "bill_return as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "' and bill.branch='".$this->session->data['branch_id']."' and bill.bill_flag='1' group by new_date,new_item_group";
		
		if (!empty($data['filter_name'])) {
				$sql110 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,-1*sum(item_gross)  as gross_sales,-1*sum((item_gross-item_stone)) as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "bill_return_items as bill_item left join " . DB_PREFIX . "bill_return as bill on bill_item.item_bill_id=bill.bill_id  left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND o.ornament_id='".$data['filter_name']."' and bill.branch='".$this->session->data['branch_id']."' and bill.bill_flag='1' group by new_date,new_item_group";
		}
		
		
		//hallmarking
		
		$sql5 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,sum(rec_weight_gross) as gross_ihallmark,sum(bill_price) as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,0 as qty FROM " . DB_PREFIX . "bill_pay_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		
		//pay goldsmith
		
		
		// $sql = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,sum(item_gross) as gross_goldsmith,sum((item_gross-item_stone)) as net_goldsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group from " . DB_PREFIX . "billp_items as bill_item left join " . DB_PREFIX . "billp as bill on bill_item.item_bill_id=bill.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id group by new_date,new_item_group";
		
		if (!empty($data['filter_name'])) {
				$sql5 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,sum(rec_weight_gross) as gross_ihallmark,sum(bill_price) as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,0 as qty FROM " . DB_PREFIX . "bill_pay_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 AND o.ornament_id='".$data['filter_name']."' and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		
		}
		
		$sql6= "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,sum(rec_weight_gross) as gross_igsmith,sum(bill_price) as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*count(*) as qty FROM " . DB_PREFIX . "bill_pay_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=0 and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		
		if (!empty($data['filter_name'])) {
				$sql6 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,sum(rec_weight_gross) as gross_igsmith,sum(bill_price) as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,0 as istock_gross,0 as istock_net ,-1*count(*) as qty FROM " . DB_PREFIX . "bill_pay_goldsmith as rec left join " . DB_PREFIX . "ornamnet as o on rec.item_group=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=0 AND o.ornament_id='".$data['filter_name']."' and rec.branch='".$this->session->data['branch_id']."' group by new_date,new_item_group";
		
		}
		
		
		//stocktransfer  reciept reciept
		
		$sql7 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,sum((bill_item.item_gross-bill_item.item_stone)) as rstock_net,sum((bill_item.item_gross)) as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=2 AND stock_name='".$this->session->data['branch_id']."' and bill_item.item_type=0  group by new_date,new_item_group";
				
		if (!empty($data['filter_name'])) {
			
			$sql7 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,sum((bill_item.item_gross-bill_item.item_stone)) as rstock_net,sum((bill_item.item_gross)) as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=2 AND o.ornament_id='".$data['filter_name']."' AND stock_name='".$this->session->data['branch_id']."' and bill_item.item_type=0   group by new_date,new_item_group";
		}	

			//stocktransfer  reciept issue

		$sql12 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,sum((bill_item.item_gross))  as istock_gross,sum((bill_item.item_gross-bill_item.item_stone)) as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=2 AND stock_name_new='".$this->session->data['branch_id']."' and bill_item.item_type=1  group by new_date,new_item_group";

		if (!empty($data['filter_name'])) {
			
			$sql12 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,sum((bill_item.item_gross)) as istock_gross,sum((bill_item.item_gross-bill_item.item_stone)) as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=2 AND o.ornament_id='".$data['filter_name']."'  AND stock_name_new='".$this->session->data['branch_id']."' and bill_item.item_type=1 group by new_date,new_item_group";
		}	



			//stocktransfer  issue

		$sql8 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,sum((bill_item.item_gross)) as istock_gross,sum((bill_item.item_gross-bill_item.item_stone)) as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 AND stock_name='".$this->session->data['branch_id']."' and bill_item.item_type=0  group by new_date,new_item_group";

		if (!empty($data['filter_name'])) {
			
			$sql8 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,0 as rstock_net,0 as rstock_gross,sum((bill_item.item_gross)) as istock_gross,sum((bill_item.item_gross-bill_item.item_stone)) as istock_net ,-1*sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 AND o.ornament_id='".$data['filter_name']."' AND stock_name='".$this->session->data['branch_id']."' and bill_item.item_type=0 group by new_date,new_item_group";
		}	

			//stocktransfer  issue reciept

		$sql13 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,sum((bill_item.item_gross-bill_item.item_stone)) as rstock_net,sum((bill_item.item_gross)) as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 AND stock_name_new='".$this->session->data['branch_id']."' and bill_item.item_type=1  group by new_date,new_item_group";

		if (!empty($data['filter_name'])) {
			
			$sql13 = "SELECT FROM_UNIXTIME(`bill_date`, '%d-%m-%Y') as new_date,0 as gross_goldsmith,0 as net_goldsmith,0 as gross_purchase,0 as net_purchase,0 as gross_hallmark,0 as net_hallmark,0 as gross_sales,0 as net_sales,0 as gross_ihallmark,0 as net_ihallmark,0 as gross_igsmith,0 as net_igsmith,o.ornamnent_name as stock,o.ornament_id as new_item_group,sum((bill_item.item_gross-bill_item.item_stone)) as rstock_net,sum((bill_item.item_gross)) as rstock_gross,0 as istock_gross,0 as istock_net ,sum(bill_item.item_qty) as qty FROM " . DB_PREFIX . "billstock_items as bill_item left join " . DB_PREFIX . "bill_rec_stock as rec on bill_item.item_bill_id=rec.bill_id left join " . DB_PREFIX . "category_description as cat on bill_item.item_code=cat.description left join " . DB_PREFIX . "ornamnet as o on cat.ornament_id=o.ornament_id where bill_date < '" . $this->db->escape($from) . "'  AND hallmark=1 AND o.ornament_id='".$data['filter_name']."' AND stock_name_new='".$this->session->data['branch_id']."' and bill_item.item_type=1   group by new_date,new_item_group";
		}